variables:
  PUSH_CI_REGISTRY_IMAGE: registry-vpc.cn-guangzhou.aliyuncs.com/ingram/shipping_proxy_web_api
  CLIENT_CI_REGISTRY_IMAGE: registry-vpc.cn-guangzhou.aliyuncs.com/ingram/shipping_proxy_web_api
  SERVER_IP: 8.134.219.28
  SERVER_USER: dku
  TARGET_DIR: /data
  COMPOST_FILE: docker-compose.yml

stages:
  - build
  - deploy

build:
  stage: 
    build
  only:
    - tags
  tags:
    - ingram
  script:
    - docker build -t "$PUSH_CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG" .
    - docker push "$PUSH_CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"

deploy:
  stage: 
    deploy
  only:
    - tags
  tags:
    - ingram
  script:
    - chmod 600 "$ID_RSA"
    - ssh -i "$ID_RSA" -o StrictHostKeyChecking=no  "$SERVER_USER"@"$SERVER_IP" "cd $TARGET_DIR ; sed -ri 's#'$CLIENT_CI_REGISTRY_IMAGE'(.*)#'$CLIENT_CI_REGISTRY_IMAGE':'$CI_COMMIT_TAG'#' $COMPOST_FILE ; docker-compose up -d"

